"""Public Brain SDK interface for CLI and agent callers."""

from packages.brain_sdk.calls import (
    CapabilityDescriptor,
    CapabilityInvokeResult,
    CapabilitySearchHit,
    CoreComponentHealth,
    CoreHealthResult,
    LmsChatResult,
    LmsChatMessage,
    LmsChatToolCall,
    LmsChatToolDefinition,
    LmsToolChatResult,
    MemoryContextBlock,
    MemoryDialogueTurn,
    MemoryProfileContext,
    MemorySessionRef,
    PolicyDecision,
    SwitchboardOperatorInstruction,
    core_health,
    describe_capability,
    describe_capabilities,
    invoke_capability,
    list_always_on_capabilities,
    lms_chat,
    lms_chat_with_tools,
    memory_assemble_context,
    memory_create_session,
    memory_get_latest_or_create_session,
    memory_record_response,
    search_capabilities,
    switchboard_poll_operator_instruction,
)
from packages.brain_sdk.client import BrainClient, BrainSdkClient
from packages.brain_sdk.config import BrainSdkConfig
from packages.brain_sdk.errors import (
    BrainConflictError,
    BrainDependencyError,
    BrainDomainError,
    BrainInternalError,
    BrainNotFoundError,
    BrainPolicyError,
    BrainSdkError,
    BrainTransportError,
    BrainValidationError,
    SdkErrorDetail,
)
from packages.brain_sdk.meta import MetaOverrides

DomainError = BrainDomainError
TransportError = BrainTransportError

__all__ = [
    "BrainClient",
    "BrainSdkClient",
    "BrainConflictError",
    "BrainDependencyError",
    "BrainDomainError",
    "BrainInternalError",
    "BrainNotFoundError",
    "BrainPolicyError",
    "BrainSdkConfig",
    "BrainSdkError",
    "BrainTransportError",
    "BrainValidationError",
    "CapabilityDescriptor",
    "CapabilityInvokeResult",
    "CapabilitySearchHit",
    "CoreComponentHealth",
    "CoreHealthResult",
    "DomainError",
    "LmsChatResult",
    "LmsChatMessage",
    "LmsChatToolCall",
    "LmsChatToolDefinition",
    "LmsToolChatResult",
    "MetaOverrides",
    "MemoryContextBlock",
    "MemoryDialogueTurn",
    "MemoryProfileContext",
    "MemorySessionRef",
    "PolicyDecision",
    "SdkErrorDetail",
    "SwitchboardOperatorInstruction",
    "TransportError",
    "core_health",
    "describe_capability",
    "describe_capabilities",
    "invoke_capability",
    "list_always_on_capabilities",
    "lms_chat",
    "lms_chat_with_tools",
    "memory_assemble_context",
    "memory_create_session",
    "memory_get_latest_or_create_session",
    "memory_record_response",
    "search_capabilities",
    "switchboard_poll_operator_instruction",
]
